#!/bin/bash

REPOS=$(cat "$(dirname "$0")/repo-list")

SCRIPT_DIR=`pwd`/scripts

FAILED_FILE="$(pwd)/failed-autopick-repos.txt"
> "$FAILED_FILE"

for i in $REPOS ; do
    if ! ( cd _WORK_/sources/sonicde/$i && $SCRIPT_DIR/git-autopick ); then
        echo "$i" >> "$FAILED_FILE"
    fi
done
