#!/bin/bash

REPOS="
    sonic-activities
    sonic-audio-applet-pulse
    sonic-decoration
    sonic-desktop-interface
    sonic-frameworks-auth
    sonic-frameworks-cmake-modules
    sonic-frameworks-core-addons
    sonic-frameworks-doctools
    sonic-frameworks-gui-addons
    sonic-frameworks-io
    sonic-frameworks-io-extras
    sonic-frameworks-keybind
    sonic-frameworks-open-collab
    sonic-frameworks-quick-ui
    sonic-frameworks-runner
    sonic-frameworks-windowsystem
    sonic-interface-libraries
    sonic-keybind-daemon
    sonic-login-manager
    sonic-mobile-interface
    sonic-network-manager
    sonic-night-light
    sonic-screen
    sonic-screen-library
    sonic-screenlocker
    sonic-sysguard
    sonic-sysguard-library
    sonic-system-info
    sonic-win
    sonic-workspace
    sonic-workspace-addons
    sonic-workspace-wallpapers
    silver-sddm
    silver-theme
"

SCRIPT_DIR=`pwd`/scripts

for i in $REPOS ; do
    ( cd _WORK_/sources/sonicde/$i && $SCRIPT_DIR/git-autopick )
done
